### PR TITLE
Adds `scale` to `MeshFile` struct

### PR DESCRIPTION
**Pull request by ferrolho**
This is a follow-up from https://github.com/JuliaRobotics/RigidBodyDynamics.jl/pull/567. I think this time I got the location of the required changes right, but I am still wondering where to apply the actual scale factor.

### CODE REVIEW

**Comment by tkoolen** [comment]
I'm not sure if adding a `scale` field to `MeshFile` is a good idea. While the `scale` tag is specific to meshes in the URDF spec, I think it'd still be nicer to make it so that the `VisualElement`s created in `visual_elements` just have the right transform. That way:
* all visual elements can be treated more uniformly down the line; with this PR as it stands, `MeshFile` is the only thing that needs special treatment, with the 'real' transform split up over the `VisualElement`'s `transform` and its `geometry.scale`. MechanismGeometries is meant as a visualizer-independent way to get appropriate geometries for a mechanism, so each possible future viewer-specific glue package would have a new chance to get it wrong (for example, we were experimenting with Makie a couple of weeks ago)
* no accompanying MeshCatMechanisms PR is needed; no need to coordinate releases.

The way things are currently set up, it's a little awkward to make it so that different `VisualElement`s associated with the same link have different transforms. The simplest (but maybe not the best) way to do this is probably:
* change `parse_geometries` to return a vector of pairs, consisting of a geometry-specific transform and the `GeometryLike` itself.
* change `parse_link!` accordingly, chaining the geometry-specific transform and the `tform` already present in that function.

But honestly, I would personally probably use this opportunity to simplify things a bit by:
* changing `parse_link!` so that it already returns a vector of `VisualElement`s, made possible by passing `body_frame` into it from `visual_elements` and `append!`ing the returned vector to `elements` in `visual_elements`.
* changing `parse_geometries` so that it already returns a vector of `VisualElement`s, made possible by passing `body_frame`, `color`, and `tform` into `parse_geometries` from `parse_link!`.

That way, it's easy to implement the `scale` change in `parse_geometries` specifically for meshes, and we can get rid of these somewhat confusing vectors of tuples-in-some-particular-order-that-you-have-to-remember as return values. I actually also suspect this may help with compilation time, which has always been a bit of an issue with this package.

**Comment by ferrolho** [comment]
I changed it according to your preference. :upside_down_face:

**Comment by tkoolen** [comment]
Thanks! Looks great. I added a test. Will merge once it passes on Travis.

**Comment by ferrolho** [comment]
You are most welcome. :)

**Pull request merged**
